#!/bin/bash -e

systemctl stop wg-quick@hydra.service
systemctl disable wg-quick@hydra.service

rm /etc/wireguard/hydra.conf

sed '/# ---- GENERATED BY proxy_setup_script.sh >>>>/,/# <<<< GENERATED BY proxy_setup_script.sh ----/d' /etc/ufw/before.rules > out
mv out /etc/ufw/before.rules
sed '/# ---- GENERATED BY proxy_setup_script.sh >>>>/,/# <<<< GENERATED BY proxy_setup_script.sh ----/d' /etc/ufw/before6.rules > out
mv out /etc/ufw/before6.rules
sed '/# ---- GENERATED BY proxy_setup_script.sh >>>>/,/# <<<< GENERATED BY proxy_setup_script.sh ----/d' /etc/default/ufw > out
mv out /etc/default/ufw
sed '/# ---- GENERATED BY proxy_setup_script.sh >>>>/,/# <<<< GENERATED BY proxy_setup_script.sh ----/d' /etc/ufw/sysctl.conf > out
mv out /etc/ufw/sysctl.conf

ufw disable
systemctl stop ufw

apt-get --autoclean remove ufw wireguard

rm /root/.ssh/authorized_keys
