#!/bin/bash

systemctl stop fastd
rm -rf /etc/fastd/hydra
ufw disable
apt-get --autoclean remove ufw fastd

sed '/# ---- GENERATED BY proxy_setup_script.sh >>>>/,/# <<<< GENERATED BY proxy_setup_script.sh ----/d' /etc/ufw/before.rules > out
cp out /etc/ufw/before.rules
sed '/# ---- GENERATED BY proxy_setup_script.sh >>>>/,/# <<<< GENERATED BY proxy_setup_script.sh ----/d' /etc/default/ufw > out
cp out /etc/default/ufw
sed '/# ---- GENERATED BY proxy_setup_script.sh >>>>/,/# <<<< GENERATED BY proxy_setup_script.sh ----/d' /etc/ufw/sysctl.conf > out
cp out /etc/ufw/sysctl.conf

rm /root/.ssh/authorized_keys
