#!/bin/bash

AUTHORIZE_KEY="${1}"
MY_IP="${2}"
VPN_DMZ_IP="${3}"
VPN_MY_IP="${4}"
VPN_NETMASK="${5}"
MY_PRIVATE_KEY="${6}"
MY_PUBLIC_KEY="${7}"
TARGET_PUBLIC_KEY="${8}"
PORTS="${9}"

mkdir -p /root/.ssh && \
echo $AUTHORIZE_KEY > /root/.ssh/authorized_keys

apt-get update && \
apt-get -yq --no-install-recommends --no-install-suggests install ufw fastd && \
ufw allow 22/tcp && \
ufw allow 10000/udp && \
mkdir -p /etc/fastd/hydra/peers

if [ $? != 0 ]; then
	return 1;
fi

cat >/etc/fastd/hydra/fastd.conf <<EOL

# Log warnings and errors to stderr
log level fatal;

# Set the interface name
interface "hydra";

# Support salsa2012+umac and null methods, prefer salsa2012+umac
method "salsa2012+umac";

# Bind to a fixed port, IPv4 only
bind 0.0.0.0:10000;

# Secret key generated by 'fastd --generate-key'
secret "${MY_PRIVATE_KEY}";
# Public: ${MY_PUBLIC_KEY}

# Set the interface MTU for TAP mode with xsalsa20/aes128 over IPv4 with a base MTU of 1492 (PPPoE)
# (see MTU selection documentation)
mtu 1194;
mode tap;

# Include peers from the directory 'peers'
include peers from "peers";

on up sync "ifconfig hydra ${VPN_MY_IP} netmask ${VPN_NETMASK} up";
on down sync "ifconfig hydra down";

EOL

cat >/etc/fastd/hydra/peers/target.conf <<EOL
key "${TARGET_PUBLIC_KEY}";
EOL

update-rc.d fastd defaults
service fastd restart


cat >>/etc/ufw/before.rules <<EOL

# NAT table
*nat
:POSTROUTING ACCEPT [0:0]
:PREROUTING ACCEPT [0:0]

EOL

for PORT in $PORTS
do
	ufw allow $PORT
	cat >>/etc/ufw/before.rules <<EOL

-A PREROUTING -d ${MY_IP} -p TCP --dport ${PORT} -j DNAT --to-destination ${VPN_DMZ_IP}
-A PREROUTING -d ${MY_IP} -p UDP --dport ${PORT} -j DNAT --to-destination ${VPN_DMZ_IP}
-A POSTROUTING -j MASQUERADE

EOL

done

echo "COMMIT" >> /etc/ufw/before.rules
echo 'DEFAULT_FORWARD_POLICY="ACCEPT"' >> /etc/default/ufw
echo net.ipv4.ip_forward=1 >> /etc/ufw/sysctl.conf

ufw --force enable
